- name: install nginx and run
  host: web
  become: yes
  tasks:
  - name: Installing nginx package
    ansible.builtin.package:
     name: nginx
     state: present
  - name: run nginx service 
    ansible.builtin.service:
      name: nginx
      state: started


    