# PLAY LEVEL VARIABLE

- name: variables 
  hosts: localhost
  vars:
    course: "code"
    trainer: "ravi"
    duration: "10000"
  tasks:
   - name: check variables 
     ansible.builtin.debug:
      msg: "hai im learning {{course}}, my trainer is {{trainer}}, duration is {{duration}}"