- name: variables 
  hosts: localhost
  vars:
    course: "devops"
    trainer: "siva"
    duration: "100"
  tasks:
   - name: check variables 
     ansible.builtin.debug:
      msg: "hai im learning {{course}}, my trainer is {{trainer}}, duration is {{duration}}"