
- name:  check variables from PLAY level
  hosts: localhost
  vars_files:
   variables.yaml
  vars_prompt:
  - name: PERSON
    prompt: "please enter your NAME"
    private: false #they can see wt u are typing
  - name: WISHES
    prompt: "please enter your WISHES"
    private: false #they can't see what u are typing
  vars:
    # PERSON: "ravi raveen FROM TASK"
    # WISHES: "mrng  FROM TASK"
  tasks:
   - name: check variables
     vars:
       PERSON: "ravi  FROM PLAY"
       WISHES:  "mrng  FROM PLAY"
     ansible.builtin.debug:
       msg: "hello {{PERSON}} good {{WISHES}}"