- name: loops 
  hosts: localhost
  become: yes
  tasks:
  - name: install or uninstall packages
    ansible.builtin.dnf:
      msg: "{{item}}" #default key word
      state: present
    loop:
    - { name: 'git', state: 'present' }
    - { name: 'mysql', state: 'present' }
    - { name: 'postfix', state: 'absent' }
    - { name: 'nginx', state: 'present' }